version: '3.8'

services:
  backend:
    build: null
    image: ${BACKEND_IMAGE:-ghcr.io/lenovo/msa/backend:latest}
    environment:
      NODE_ENV: production
      # Production API URLs for frontend
      REACT_APP_API_URL: https://beta.kaizenacademy.io/api
      REACT_APP_SOCKET_URL: https://beta.kaizenacademy.io

  frontend:
    build: null
    image: ${FRONTEND_IMAGE:-ghcr.io/lenovo/msa/frontend:latest}
    environment:
      REACT_APP_API_URL: https://beta.kaizenacademy.io/api
      REACT_APP_SOCKET_URL: https://beta.kaizenacademy.io

  rag-service:
    build: null
    image: ${RAG_IMAGE:-ghcr.io/lenovo/msa/rag-service:latest}
    profiles:
      - rag